### ISSUE TITLE
Could you please rename the PyPi package to "apify-unofficial"

### ISSUE THREAD

**Issue by jancurn** [ctrl-q/apify#1]
Hi there, awesome job, many thanks for creating this library! However, I'd like to ask you one thing. Please can you rename the PyPi package to something like `apify_unofficial` or something like that? The reason is it might confuse our users since the `apify` package for Node.js is the Apify SDK, and `apify_client` is for the official API client for Node.js. We'd like to create equivalents of these packages also in Python. It's our mistake that we didn't allocate the package names earlier - we'll fix that promptly.

Many thanks in advance! Please contact me on my email if you have any questions.

**Comment by ctrl-q** [comment]
Done. Please validate #2 and I'll upload to PyPi

**Comment by jancurn** [comment]
Awesome, many thanks. I'm not a Python expert, but maybe you'll also need to rename the directory from `apify` to `apify_unofficial`. Anyway, after you do this, could you also delete the `apify` package from PyPi?

**Comment by ctrl-q** [comment]
Yep you're right. Should be good now. Please close the issue if all is good.

**Comment by jancurn** [comment]
Everything seems fine now, many thanks for your help and good work!
